# Site settings
title: Sheetal wire products  
email: agrawalsheetalwirepro@rediffmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "SheetalWireProducts.github.io" # the base hostname & protocol for your site

# User setting
owner: Sheetal Agrawal
email: agrawalsheetalwirepro@rediffmail.com
#facebook_username:
#twitter_username:
github_username: SheetalWireProducts
address: 711/4, Industrial Area 
  - line: Rawabhata, Raipur (C.G)
 # - line:
  # Feel free to add more lines here 
telephone: +91-9300291347, +91-6265898703
copyright:SheetalWireProducts

# API settings
google_api_key:

# Build settings
markdown: kramdown
